title: "Selected Works"
description: "caveat emptor"
author: tkukurin

copyright: ""
mathjax: true

permalink: "/:title"
date_format: "%b %-d, %Y"

markdown: kramdown
mathjax: true

exclude: ["*.ipynb"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# unsupported :(
# plugins:
#  - jekyll-jupyter-notebook

